### ISSUE TITLE
The original MATLAB code

### ISSUE THREAD

**Issue by longtimenosee910** [quarterwave0/LithographySimulator#1]
Hi!excuse me,Can you share the original MATLAB code with me?Thank you very much

**Comment by quarterwave0** [comment]
The code is attached, as sent by Prof. Gau. I don't really have the licensing to post this, so if someone takes issue please email me -- but seeing as the code is presently unavailable from Code Ocean even with academic affiliation, this can hopefully stop the emails.

[Re__Code_for_Ultra-Fast_aerial_image_simulation_paper.zip](https://github.com/user-attachments/files/15923130/Re__Code_for_Ultra-Fast_aerial_image_simulation_paper.zip)

**Comment by longtimenosee910** [comment]
Thanks a lot
